Repository chipsalliance/treadle, pull requests merged in 2019-08, with the labels that each got.

#117 Fix REPL not running because of duplicated annotation flag
  src/main/scala/treadle/repl/ReplOptions.scala
  src/main/scala/treadle/repl/TreadleReplCli.scala
  src/main/scala/treadle/stage/TreadleStage.scala
Labels: bug, cleanup

#125 Developer reported problem with Cat PrimOp
  src/main/scala/treadle/executable/BigPrimOps.scala
  src/main/scala/treadle/executable/IntOps.scala
  src/main/scala/treadle/executable/LongPrimOps.scala
  src/test/scala/treadle/BitTwiddlingUtils.scala
  src/test/scala/treadle/primops/CatBitsHeadTail.scala
Labels: bug, release issue

#123 Test for async reset
  src/test/scala/treadle/asyncreset/AsyncResetNativeSpec.scala
Labels: enhancement

#126 Stale black box code and comments are confusing
  src/main/scala/treadle/executable/BlackBoxCycler.scala
  src/main/scala/treadle/executable/DataStorePlugIn.scala
  src/main/scala/treadle/executable/Scheduler.scala
Labels: cleanup

#128 ExpressionCompiler: make manual clocking work with asClock(clk)
  src/main/scala/treadle/executable/ExpressionCompiler.scala
  src/main/scala/treadle/executable/SymbolTable.scala
  src/test/scala/treadle/ClockedManuallySpec.scala
Labels: DO NOT MERGE
