Repository chipsalliance/treadle, pull requests merged in 2021-02, with the labels that each got.

#264 Add scalafmt plugin to add sbt tasks for scalafmt
  project/plugins.sbt
Labels: enhancement

#294 Sorts repl help mesage
  src/main/scala/treadle/TreadleRepl.scala
Labels: enhancement

#298 Use Statement Names from Firrtl
  src/main/scala/treadle/executable/SymbolTable.scala
  src/main/scala/treadle/stage/phases/HandleFormalStatements.scala
  src/main/scala/treadle/stage/phases/PrepareAst.scala
  src/test/resources/HasCoverStatements.fir
  src/test/scala/treadle/FormalCoverSpec.scala
  src/test/scala/treadle/VerificationSpec.scala
Labels: Please Merge

#228 Remove Driver. Follow-up to #226
  src/main/scala/treadle/Driver.scala
  src/main/scala/treadle/TreadleRepl.scala
  src/main/scala/treadle/TreadleTester.scala
  src/main/scala/treadle/repl/ReplConfig.scala
  src/main/scala/treadle/repl/ReplVcdController.scala
  src/main/scala/treadle/vcd/VCD.scala
  src/main/scala/treadle/vcd/VCDConfig.scala
  src/main/scala/treadle/vcd/VcdOptions.scala
  src/main/scala/treadle/vcd/VcdStage.scala
  src/test/scala/treadle/vcd/VCDSpec.scala
Labels: Please Merge, enhancement

#301 build: remove explicit dependencies on scopt and json libraries
  build.sbt
  build.sc
Labels: Please Merge

#302 junit is a a fossil, remove it from build.sbt
  build.sbt
Labels: cleanup
