Repository chipsalliance/treadle, pull requests merged in 2021-06, with the labels that each got.

#332 remove testOnly, since upstream implemented it.
  build.sc
Labels: Please Merge

#336 Finish support for BuildInfo
  build.sbt
  project/plugins.sbt
Labels: Please Merge, enhancement

#330 Update scala-library to 2.12.14
  .github/workflows/test.yml
  build.sbt
  src/test/scala/treadle/primops/ShlShrDshlDshr.scala
Labels: Please Merge

#337 Make MultiTopLevelClockSpec work
  src/test/scala/treadle/chronometry/MultiTopLevelClockSpec.scala
Labels: Please Merge, bug

#328 Update scala-library to 2.13.6
  build.sbt
Labels: Please Merge

#339 Cleans up `Stop` handling in Treadle
  src/main/scala/treadle/TreadleTester.scala
  src/main/scala/treadle/executable/ExecutionEngine.scala
  src/main/scala/treadle/executable/ExpressionCompiler.scala
  src/main/scala/treadle/executable/StopOp.scala
  src/main/scala/treadle/executable/TreadleException.scala
  src/test/scala/treadle/PrintStopSpec.scala
  src/test/scala/treadle/StopBehaviorSpec.scala
  src/test/scala/treadle/VerificationSpec.scala
Labels: enhancement
